@startuml partie2

' entity "EntryPriorFile" as entPri {
'     loi de Poisson de paramètre 0.7
' }
' entity "EntryNormFile" as entOrd {
'     loi de Poisson de paramètre 2
' }
' entity "Service" as serv {
'     loi décrite par le tableau
' }

' entPri ||--|| serv
' entOrd ||--|| serv



@enduml