const TYPE_CLIENT = {
    ORDINAIRE: 0,
    RELATIF: 1,
    ABSOLU: 2,
};

const PROPORTION_ABSOLU = 0.3;

const POISSON_CLIENTS_PRIORITAIRES = 0.7;
const POISSON_CLIENTS_ORDINAIRES = 2;

const COUT_HORAIRE_SYSTEME = {
    ORDINAIRE: 25,
    RELATIF: 35,
    ABSOLU: 45,
};

const COUT_HORAIRE_OCCUPATION = {
    ORDINAIRE: 30,
    PRIORITAIRE: 32,
};

const COUT_HORAIRE_INNOCUPATION = 18;

const PERTE = {
    PRIORITAIRE: 20,
    ORDINAIRE: 15,
};

export {
    TYPE_CLIENT,
    POISSON_CLIENTS_ORDINAIRES,
    POISSON_CLIENTS_PRIORITAIRES,
    COUT_HORAIRE_SYSTEME,
    COUT_HORAIRE_OCCUPATION,
    COUT_HORAIRE_INNOCUPATION,
    PERTE,
    PROPORTION_ABSOLU,
};
